### ISSUE TITLE
ValidationError: Impersonation by google____vedavaapi2@gmail.com as pyCV2 not allowed for this user.

### ISSUE THREAD

**Issue by vvasuki** [vedavaapi/ullekhanam-ui#4]
Initial problem reported by @manikanta29788 :
Payload sent - http://jsoneditoronline.org/?id=f1546c732da77c738d64648bec5a23e4 .

Initial response:
"If you want to just add a text annotation - make that the content, and set its targets field appropriately"

**Comment by VarMit24** [comment]
Updated payload - http://jsoneditoronline.org/?id=5dcf57a84ae97ccd86b71454010c86da

**Comment by vvasuki** [comment]
The problem with that payload is the following:
```
"source": {
        "source_type": "user_supplied",
        "id": "pyCV2",
        "jsonClass": "DataSource"
      },
```
The user `google____vedavaapi2@gmail.com` is pretending to be a user with "pyCV2" who had written this ImageAnnotation in the first place. So, one would need to omit "id": "pyCV2" in order to expect the user `google____vedavaapi2@gmail.com` to take over that annotation for editing or deletion (This ability is yet to be implemented in the backend).

But, let us take a step back and think: How do we create a text annotation which targets an image annotation with the id "59f92075caae641d29ba80fa" (whoever created it)? Elaborating on the earlier suggestion "If you want to just add a text annotation - make that the content, and set its targets field appropriately", you would need to simply change the payload as shown in http://jsoneditoronline.org/?id=9f8e7261ae0615507399fc427934cfcc :

![image](https://user-images.githubusercontent.com/2664797/33393644-b12fd64a-d4f4-11e7-8577-a53b384284aa.png)

Note that you simply set the targets field appropriately - no need to include the original image annotation which you don't seem to want to change anyway. Can you see if this payload works?

**Comment by vvasuki** [comment]
maNikaNTha on whatsapp indicates that this issue is solved.

**Comment by VarMit24** [comment]
i tried posting the above payload...the post entity API works fine but when i'm retrieving the targets again the saved text annotation is not mapped with the image annotation instead it created a new target without image annotation and it is affecting the canvas rendering. Please look into this.

Below is the post entity payload
http://jsoneditoronline.org/?id=e7c7110e9c0f5bdc924f72ce2be2527e

**Comment by vvasuki** [comment]
If you wanted the text annotation with an image annotation, why are you setting the target in the payload to be 59f91d9acaae641d29ba7ef2 (which is a BookPortion page object)? You need to set the target field to point to the image annotation with which you wish to associate the text annotation you're creating. (Please don't hesitate to reopen if there are further questions! I appreciate your using the appropriate issue thread.)
