### ISSUE TITLE
How to save a new target created by a user?

### ISSUE THREAD

**Issue by VarMit24** [vedavaapi/ullekhanam-ui#9]
Will POST entity API does the above, if yes then what will be the payload for the same?

**Comment by vvasuki** [comment]
What exactly do you mean by a "new target"? A new image annotation? Whatever it is, just set it in the content field of the first JsonObjectNode in the list you send to the POST entity API as shown below:

![image](https://user-images.githubusercontent.com/2664797/33393644-b12fd64a-d4f4-11e7-8577-a53b384284aa.png)

Don't forget to adjust the targets field appropriately though. In case of ImageAnnotation, this must be the _id of a BookTarget object.
